"""Add break_minutes to daily availability

Revision ID: 9f8e7d6c5b4a
Revises: b16bfaa67793
Create Date: 2026-08-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8e7d6c5b4a'
down_revision = 'b16bfaa67793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'daily_availability',
        sa.Column(
            'break_minutes',
            sa.Integer(),
            nullable=False,
            server_default='15'
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_availability', 'break_minutes')
    # ### end Alembic commands ###
